site_name: "Todoist Python SDK"

repo_url: https://github.com/Doist/todoist-api-python/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-auto
        name: Follow system preference
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/doistdevs
    - icon: fontawesome/brands/github
      link: https://github.com/doist

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            backlinks: true
            filters: ["!^_"]
            show_symbol_type_toc: True
            signature_crossrefs: true
            unwrap_annotated: true
