name: Publish docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.11

      - name: Install project
        run: uv sync --group docs

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy
