name: Run tests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.11

      - name: Install project
        run: uv sync --group dev

      - name: Test with pytest
        run: uv run pytest
